export default {
    alert: {
        ansettelsesdetaljerEndret: "Ansettelsesdetaljer fra arbeidsgiver {} er endret",
        antallArbeidsforholdEndret: "Antall arbeidsforhold for {} har blitt endret",
        antallBarnetilleggPerioderEndret: "Antall barnetillegg perioder har blitt endret",
        antallSivilstandsperioderEndret: "Antall sivilstandsperioder har blitt endret i Folkeregisteret",
        antallUtvidetBarnetrygdPerioderEndret: "Antall utvidet barnetrygd perioder har blitt endret",
        barnSomHarBlittLagtInn: "Barn som har blitt lagt inn i nye opplysninger fra Folkeregisteret:",
        barnSomIkkeFinnes: "Barn som ikke finnes i nye opplysninger fra Folkeregisteret:",
        beløpEndret: "Beløp for en eller flere perioder har blitt endret",
        endretVirkningstidspunkt:
            "Virkningstidspunktet er endret. Dette kan påvirke beregningen. Boforhold og inntekt må manuelt vurderes på nytt",
        endringer: "Følgende endringer har blitt utført:",
        enEllerFlereBoforholdPerioderEndret: "En eller flere perioder har blitt endret for barn med ident - {}",
        enEllerFlereInntektPerioderLagtTil: "En eller flere inntekt perioder har blitt lagt til rolle med ident - {}",
        enEllerFlereSivilstandPerioderEndret: "En eller flere sivilstandsperioder har blitt endret",
        feilIPeriodisering: "Feil i periodisering",
        flereBarnRegistrertPåAdresse: "Det er flere barn registret på samme adresse i Folkeregisteret.",
        fullførRedigering: "Fullfør redigering",
        færreBarnRegistrertPåAdresse: "Det er færre barn registrert på samme adresse i Folkeregisteret.",
        ingenInntekt: "Ingen inntekt funnet",
        manglerVirkningstidspunkt: "Mangler virkningstidspunkt",
        minstEnInntektMindre: "Det er minst en inntekt som legges til grunn mindre for person med ident - {}",
        nyeOpplysninger: "Nye opplysninger tilgjengelig. Sist hentet {}",
        overlappendePerioder: "Du har overlappende perioder",
        periodeUnderRedigering: "Det er en periode som er under redigering. Fullfør redigering eller slett periode.",
        sluttdatoForArbeidsforholdEndret: "Sluttdato for arbeidsforhold {} er endret fra {} til {}",
        startdatoForArbeidsforholdEndret: "Startdato for arbeidsforhold {} er endret",
        stillingprosentEndret: "Stillingprosent fra arbeidsgiver {} er endret fra {}% til {}%",
        sumEndret: "Sum for {} har blitt endret for rolle med ident - {} fra {} til {}",
        underArbeit:
            "Denne siden er under arbeid og er ikke klar for testing. Du vil få beskjed når du kan begynne å teste denne siden.",
    },
    error: {
        datoIkkeGyldig: "Dato er ikke gyldig",
        datoMåFyllesUt: "Dato må fylles ut",
        datoMåSettesManuelt: "Dato må settes manuelt",
        datoMåVæreDenSisteIMåneden: "Dato må være den siste i måneden",
        datoMåVæreDenFørsteIMåneden: "Dato må være den første i måneden",
        framoverPeriodisering: "Det kan ikke periodiseres fremover i tid.",
        fatteVedtak: "Det skjedde en feil ved fatte vedtak",
        feilmelding: "Det har skjedd en feil",
        hentingAvNotat: "Det skjedde en feil ved henting av notat",
        hullIPerioder:
            "Det er perioder i beregningen uten status. Legg til en eller flere perioder som dekker periode fra {} til {}",
        identMåFyllesUt: "Ident må fylles ut",
        ingenLoependePeriode: "Det er ingen løpende status i beregningen.",
        navnMåFyllesUt: "Navn må fylles ut",
        kunneIkkeBeregneSivilstandPerioder: "Kunne ikke beregne sivilstand tidslinje basert på virkningstidspunkt.",
        personFinnesIkke: "Finner ikke person med ident: {}",
        tomDatoKanIkkeVæreFørFomDato: "Tom dato kan ikke være før fom dato",
        ugyldigBoststatusFør18: "Ugyldig boststatus for periode etter barnet har fylt 18 år.",
        ugyldigBoststatusEtter18: "Ugyldig bosstatus for periode før barnet har fylt 18 år.",
    },
    label: {
        angreSisteSteg: "Angre siste steg",
        antallBarn: "Antall barn i husstand",
        arbeidsgiver: "Arbeidsgiver",
        avslag: "Avslag",
        avbryt: "Avbryt",
        barn: "Barn",
        begrunnelseKunINotat: "Begrunnelse (kun med i notat)",
        begrunnelseMedIVedtaket: "Begrunnelse (med i vedtaket og notat)",
        beløp: "Beløp",
        beløpMnd: "Beløp (mnd)",
        beløp12Mnd: "Beløp (12 mnd)",
        beskrivelse: "Beskrivelse",
        fatteVedtakButton: "Fatte vedtak",
        forskudd: "Forskudd",
        fraDato: "Fra dato",
        fraOgMed: "Fra og med",
        fødselsdato: "Fødselsdato",
        fødselsnummerDnummer: "Fødselsnummer/d-nummer",
        gåVidere: "Gå videre",
        inntekt: "Inntekt",
        jaSlett: "Ja, slett",
        kilde: "Kilde",
        leggTilPeriode: "+ Legg til periode",
        lukk: "Lukk",
        lønnsendring: "Lønnsendring",
        lønnsinntektMedTrygdeavgiftspliktOgMedTrekkplikt: "Lønnsinntekt med trygdeavgiftsplikt og med trekkplikt: {}",
        mottattdato: "Mottat dato",
        navn: "Navn",
        notatButton: "Vis notat",
        nåværendeArbeidsforhold: "Nåværende arbeidsforhold",
        oppdater: "Oppdater",
        periode: "Periode",
        resultat: "Resultat",
        sivilstand: "Sivilstand",
        sivilstandBM: "Sivilstand til BM",
        stilling: "Stilling",
        sum: "Sum",
        taMed: "Ta med",
        tilOgMed: "Til og med",
        totalt: "Totalt",
        type: "Type",
        status: "Status",
        søknadstype: "Søknadstype",
        søknadfra: "Søknad fra",
        søktfradato: "Søkt fra dato",
        virkningstidspunkt: "Virkningstidspunkt",
        årsak: "Årsak",
    },
    loading: "venter...",
    refresh: "Last på nytt",
    select: {
        barnPlaceholder: "Velg barn",
        inntektPlaceholder: "Velg type inntekt",
        årsakAvslagPlaceholder: "Velg årsak/avslag",
    },
    skjermbildeNavn: "Søknad om forskudd",
    title: {
        arbeidsforhold: "Arbeidsforhold",
        barn: "Barn",
        barnetillegg: "Barnetillegg (for bidragsbarnet, per måned i tillegg til inntekter)",
        barnOver18: "Barn over 18 år",
        begrunnelse: "Begrunnelse",
        boforhold: "Boforhold",
        copyButton: "Kopier {}",
        detaljer: "Detaljer",
        inntekt: "Inntekt",
        kontantstøtte: "Kontantstøtte",
        sivilstand: "Sivilstand",
        sjekkNotat: "Sjekk notat",
        skattepliktigeogPensjonsgivendeInntekt: "Skattepliktige og pensjonsgivende inntekt",
        småbarnstillegg: "Småbarnstillegg",
        opplysningerFraFolkeregistret: "Opplysninger fra Folkeregistret",
        oppsummering: "Oppsummering",
        utvidetBarnetrygd: "Utvidet barnetrygd",
        vedtak: "Vedtak",
        virkningstidspunkt: "Virkningstidspunkt",
    },
    varsel: {
        beregneFeil: "Kunne ikke beregne forskudd",
        ukjentNavn: "UKJENT",
        bekreftFatteVedtak: "Jeg har sjekket notat og opplysninger i søknaden og bekrefter at opplysningene stemmer.",
        vedtakNotat:
            "Så snart vedtaket er fattet, kan den gjenfinnes i sakshistorikk. Notatet blir generert automatisk basert på opplysningene oppgitt.",
        ønskerDuÅSlette: "Ønsker du å slette?",
        ønskerDuÅSletteBarnet: "Ønsker du å slette barnet som er lagt til i beregningen?",
    },
    barnetHarFylt18SjekkBostatus: "Barnet har fylt 18 år i løpet av perioden. Sjekk om bostatus til barnet er riktig",
    resetTilOpplysninger: "Reset til opplysninger fra offentlig register",
    år: "år",
};
